### ISSUE TITLE
Ipv6 static adresses not working 

### ISSUE THREAD

**Issue by mzhirnov1** [containers/podman-machine-cni#10]
Hi! We are trying to use the Ipv6 static address but with no luck.  Static ipv4 is working. Can you suggest anything?

**Comment by Luap99** [comment]
What do you mean by static addresses? How do you use this plugin?

**Comment by mzhirnov1** [comment]
Here is example for docker https://stackoverflow.com/questions/27937185/assign-static-ip-to-docker-container 

I need to bind ipv6 address to container. We have service which use Ipv6 as Client ID so I need to have IP available if I stop container and start again

**Comment by Luap99** [comment]
What command are you running?
Port forwarding for a specific ip does not work at the moment see https://github.com/containers/podman/issues/11528

**Comment by mzhirnov1** [comment]
podman run --name $NAME$i --net $NET -d elve/node-web-app

**Comment by mzhirnov1** [comment]
cat /etc/cni/net.d/ipv6_whatsup.conflist 
{
   "cniVersion": "0.4.0",
   "name": "ipv6_whatsup",
   "plugins": [
      {
         "type": "bridge",
         "bridge": "cni-podman1",
         "isGateway": true,
         "ipMasq": true,
         "hairpinMode": true,
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "::/0"
               },
               {
                  "dst": "0.0.0.0/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "2a01:3f8:10b:a17:3::/80",
                     "gateway": "2a01:3f8:10b:a17:3::1"
                  }
               ],
               [
                  {
                     "subnet": "10.89.0.0/22",
                     "gateway": "10.89.0.1"
                  }
               ]
            ]
         }
      },
      {
         "type": "portmap",
         "capabilities": {
            "portMappings": true
         }
      },
      {
         "type": "firewall",
         "backend": ""
      },
      {
         "type": "tuning"
      },
      {
         "type": "dnsname",
         "domainName": "dns.podman",
         "capabilities": {
            "aliases": true
         }
      }
   ]

**Comment by mzhirnov1** [comment]
this configuration use DHCP. But I need static IPv6 .

**Comment by mzhirnov1** [comment]
I want to assign IPv6 when I start container. Same as in Docker
https://docs.podman.io/en/latest/markdown/podman-run.1.html 

![image](https://user-images.githubusercontent.com/47160263/133314837-c32ccea5-373a-42af-b320-babe3f97ddcc.png)

**Comment by Luap99** [comment]
This repository is about issues with podman-machine port forwarding. If you have problem with podman please fill a bug against podman. The ipv6 bug is already tracked there https://github.com/containers/podman/issues/7511.
