### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Luap99** [containers/podman-machine-cni#4]
We need tests for this plugin.

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by Luap99** [comment]
What we need to have is
1. make sure the code compiles
2. run golangci-lint
3. run vendor check
4. run tests (first write some, this is the hard part because this requires a running gvproxy)

**Comment by Luap99** [comment]
>     4. run tests (first write some, this is the hard part because this requires a running gvproxy)

PR #6 adds unit tests when this is merged it only needs to be wired into some form of CI.
