### ISSUE TITLE
udp port forwarding not working

### ISSUE THREAD

**Issue by Luap99** [containers/podman-machine-cni#8]
This is blocked on https://github.com/containers/gvisor-tap-vsock/issues/37. At the moment gvproxy cannot expose udp ports.

This plugin doesn't take the protocol into account and always exposes a tcp port even when udp was requested. Should this plugin error when udp was requested until gvproxy supports udp?

**Comment by nutcr4cker** [comment]
Hi, will it be implemented in near future? I see the underlying issue is resolved now.

**Comment by Luap99** [comment]
see https://github.com/containers/podman/pull/12283

**Comment by rhatdan** [comment]
@Luap99 should we archive this repo?

**Comment by Luap99** [comment]
> @Luap99 should we archive this repo?

Not yet, lets wait until the podman PR makes it into a release (4.0).
